---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test_ubuntu_focal
    image: ubuntu:focal
    command: '/lib/systemd/systemd'
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
provisioner:
  name: ansible
verifier:
  name: ansible
